version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: ./web/
    ports:
      - "8011:8000"
    volumes:
      - ./web:/code
    command: ["/code/wait-for-it.sh", "db:5432", "--", "python",  "manage.py",  "runserver",  "0.0.0.0:8000"]
    depends_on:
      - db
